# Generated by Django 5.2 on 2025-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
